dist: trusty
language: go
go:
- 1.14
services:
- postgresql
- docker
addons:
  postgresql: '11.6'
go_import_path: github.com/makerdao/vdb-oasis-transformers
before_install:
- make installtools
- bash ./scripts/install-postgres-11.sh
- sudo apt-get update && sudo apt-get install python3-pip -y
- sudo pip3 install awscli
script:
- set -e
- scripts/check_config.sh
- env GO111MODULE=on make test
- env GO111MODULE=on make integrationtest
deploy:
- provider: script
  script: bash ./.travis/deploy.sh prod
  on:
    branch: main
- provider: script
  script: bash ./.travis/deploy.sh staging
  on:
    branch: develop
notifications:
  email: false
